

export const bannerConstants = {
    GET_ALL_BANNER_REQUEST: 'GET_ALL_BANNER_REQUEST',
    GET_ALL_BANNER_SUCCESS: 'GET_ALL_BANNER_SUCCESS',
    GET_ALL_BANNER_FAILURE: 'GET_ALL_BANNER_FAILURE',
}

export const aboutConstants = {
    GET_ALL_ABOUT_REQUEST: 'GET_ALL_ABOUT_REQUEST',
    GET_ALL_ABOUT_SUCCESS: 'GET_ALL_ABOUT_SUCCESS',
    GET_ALL_ABOUT_FAILURE: 'GET_ALL_ABOUT_FAILURE',
}

export const feedbackConstants = {
    ADD_USER_FEEDBACK_REQUEST: 'ADD_USER_FEEDBACK_REQUEST',
    ADD_USER_FEEDBACK_SUCCESS: 'ADD_USER_FEEDBACK_SUCCESS',
    ADD_USER_FEEDBACK_FAILURE: 'ADD_USER_FEEDBACK_FAILURE'
}